sudo: required
services:
    - docker

before_install:
    - docker build -t ruslanmalogulko/react-test -f ./client/Dockerfile.dev ./client

script:
    CI=true && docker run ruslanmalogulko/react-test npm test -e npm test -- --coverage

after_success:
    - docker build -t ruslanmalogulko/multi-client ./client
    - docker build -t ruslanmalogulko/multi-nginx ./nginx
    - docker build -t ruslanmalogulko/multi-server ./server
    - docker build -t ruslanmalogulko/multi-worker ./worker

    # Log into Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push images to docker hub
    - docker push ruslanmalogulko/multi-client
    - docker push ruslanmalogulko/multi-nginx
    - docker push ruslanmalogulko/multi-server
    - docker push ruslanmalogulko/multi-worker
